### ISSUE TITLE
Some tiny suggestions

### ISSUE THREAD

**Issue by Mer1997** [jcanaviri42/estructuras-de-datos#1]
Hey, buddy, I just looked at the basics.cpp you submitted yesterday.

I don't know where you got the course from, but if you really want to learn C++ instead of C with class, you should change a better course.

A good course will teach you to write:
```cpp
auto main(void) -> int {
    return 0;
}
```
or
```cpp
int main(void) {
    return 0;
}
```
instead of
```cpp
int main() {
    return 0;
}
```

A good course will teach you to use using instead of typedef:
```cpp
using ull = unsigned long long;
```

**Comment by jcanaviri42** [comment]
Ok, I'll try to apply the suggested changes.
